### ISSUE TITLE
Suggestion: Add static methods naturalOrder() and reverseOrder() to LongComparator, etc.

### ISSUE THREAD

**Issue by kevinarpe** [mintern-java/primitive#11]
First, let me say: This is a great small library.  Nothing to be 'ashamed' about the copy-paste-edit of TimSort, etc.  Java should include these methods already!

Suggestion:
Similar to Java 8's Comparator::naturalOrder() and reverseOrder(), you may want to add something similar to your LongComparator, etc.

Example: (Java 8-specific, but could be rewritten for Java 6)

```java

    public interface LongComparator {

        int compare(long l1, long l2);

        public static LongComparator naturalOrder() {
            return Long::compare;
        }

        public static LongComparator reverseOrder() {
            return (long l1, long l2) -> Long.compare(l2, l1);
        }
    }
```

**Comment by mintern** [comment]
Thanks for the suggestion! I definitely see the value of these convenience methods, but unfortunately, static interface methods weren't added until Java 8. Supporting this feature would force this library to discontinue support for Java 6 and 7.

I don't personally have a strong reason to continue supporting Java 6 and 7, so I will look forward to adding this support in the future. For now, though, I don't feel that this particular feature is compelling enough on its own to warrant that change.

**Comment by kevinarpe** [comment]
Good point about Java 6.  As a public API, it might be nice to keep Java 6 compatibility.

Alternative idea to keep Java 6 compatibility:

```java
public final class LongComparators {

    private LongComparators() {}

    private static final LongComparator NATURAL_ORDER = new LongComparator() {
                @Override
                public int compare(long l1, long l2) {
                    return Long.compare(l1, l2);
                }
            };
    public static LongComparator naturalOrder() { return NATURAL_ORDER; }

    // ...
}        
```

While less than ideal a new class means 'harder to discover'.  I find very modern IDEs can already well-hint the presence of these static methods.

**Comment by mintern** [comment]
I prefer not to do that. I think your original suggestion is the right way to do it since it is similar to Java 8's convenience methods. If I add it in a utility class, then I have to deprecate it when I change it to be "the right way" (the way you originally suggested).

Once a stable Java 9 is released, I'll create a new version that's only compatible with Java 8 and up.

**Comment by mintern** [comment]
Fixed: https://github.com/mintern-java/primitive/commit/6a36967b52d259213068e2ae7fee6a1b5423222b
