### ISSUE TITLE
Backport TimSort bugfix

### ISSUE THREAD

**Issue by phraktle** [mintern-java/primitive#2]
The recently discovered bug in TimSort and the corresponding fix should be backported.

See:
 * http://envisage-project.eu/proving-android-java-and-python-sorting-algorithm-is-broken-and-how-to-fix-it/
 * https://bugs.openjdk.java.net/browse/JDK-8072909

**Comment by mintern** [comment]
Thanks! It's on my todo list, but I'm traveling right now.

**Comment by mintern** [comment]
Fixed by e1a5bf8.

**Comment by mintern** [comment]
FYI: The current Java release includes a still-broken "fix". The fix I used came from the [latest JDK9 source](http://hg.openjdk.java.net/jdk9/dev/jdk/file/e276aa5b8a4b/src/java.base/share/classes/java/util/TimSort.java).
