### ISSUE TITLE
Unstable sort used by default

### ISSUE THREAD

**Issue by phraktle** [mintern-java/primitive#3]
The readme and javadoc claims that stable sort is used by default. However, the implementation actually invokes sort with stable=false.

See
https://github.com/mintern-java/primitive/blob/master/src/main/fmpp/templates/Primitive.java.ft#L121

**Comment by mintern** [comment]
Good catch! I plan to fix both this and #2 before the end of the weekend. In that fix (1.2) I'll change the invocation to stable=true.

Long-term, though, it seems like needing stability is the exception. I'm considering releasing 2.0 where unstable sort is the default. From your usage, do you have a strong preference one way or the other?

**Comment by phraktle** [comment]
I needed the stable sort variant, but I don't have a strong opinion either way, just wanted to highlight the inconsistency :)

**Comment by phraktle** [comment]
An argument could be made for keeping stable sort the default: Java performs a stable sort in all cases where you can supply a Comparator, so if you ported sorting a List<Integer>#sort to Primitve.sort(int[]), you would expect the comparator semantics to remain the same.

**Comment by mintern** [comment]
Thanks for the input. That's a good point, and I tend to agree with you from a consistency standpoint.

From a practical standpoint, though, one primitive is (usually) no different from another. For many use cases (e.g., sorting in reverse order) having a stable primitive sort is irrelevant. Usually, you know if you need a stable sort, so it might be nice for the simplest call to be the (typically faster) unstable sort.

It's hard for me to actually think of a use case where equivalent primitive values getting swapped makes a difference. If you don't mind sharing, could you give me an idea of how you're using it?

**Comment by mintern** [comment]
The original issue is fixed by 37263a6, so I'm closing this. But I'm happy to continue the discussion about which algorithm is more appropriate to use as the default sort algorithm.

**Comment by phraktle** [comment]
I have a struct encoded as 64 bit longs, so it's basically a value object without pointer chasing and no overhead.

Not sure how common this might be, but it feels like that when you need a Comparator for sorting primitives, chances are you are looking to sort by multiple factors. (For a simple reverse order I would probably not turn to this library :)

**Comment by phraktle** [comment]
In any scenario, where you have a sorted list that you would re-sort by a secondary key, a stable sort makes sense. Many data processing scenarios have this pattern, for example handling posting lists in an inverted index or external sorts during a map/reduce.

**Comment by mintern** [comment]
Oh, I see! Thanks for the explanation. For some reason, I was thinking that two different numbers wouldn't compare to 0, but of course they can. With that in mind, I think that stable makes a lot of sense as the default when you offer comparators, as you suggested.

**Comment by mintern** [comment]
Thanks again for your input and for your bug reports!
